@REM An Adventure Maker (tm) product. Copyright & instructions in Readme.txt
@ECHO OFF
SET &amg=nhk
SET &l5w=v7w
SET &j5w=d5w
SET &d5w=a5w
SET &f5w=l5w
SET &g5w=l5w

 SET &&l5w=u7w
 REM Is the question still left?
 SET &&a5w=b7w

   SET &&k5w=y7w
   SET &&s5w=b7w

 ECHO Welcome to 'The Terror Of Mecha Godzilla - The True Story'!
 ECHO MechaGodzilla is on a mad rampage in the city of Tokyo. It is your job to
 ECHO find him and stop him. He has already killed 7 people. You must stop him
 ECHO before he kills 8 000 000. Go now!
 ECHO.
 LOOK

  :l5w
